-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.country;

CREATE TABLE IF NOT EXISTS public.country
(
    name text COLLATE pg_catalog."default" NOT NULL,
    year numeric(4, 0) NOT NULL,
    code character varying(3) COLLATE pg_catalog."default",
    gdp_growth_annual numeric,
    gdp_cap_growth numeric,
    health_exp_cap numeric,
    health_exp_gdp numeric,
    gdp_cap_ppp numeric,
    gdp_ppp numeric,
    edu_exp numeric,
    nat_resc_rent numeric,
    women_seats numeric,
    women_bus_law_score numeric,
    life_exp numeric,
    inf_mort numeric,
    rd_exp numeric,
    hi_tech_export numeric,
    internet numeric,
    ict_good_exp numeric,
    ict_good_imp numeric,
    ict_ser_exp numeric,
    gini numeric,
    ease_bus_score numeric,
    milt_exp numeric,
    total_score numeric,
    pol_rights numeric,
    civil_lib numeric,
    CONSTRAINT country_pkey PRIMARY KEY (name, year)
);

DROP TABLE IF EXISTS public.dyad;

CREATE TABLE IF NOT EXISTS public.dyad
(
    source_country text COLLATE pg_catalog."default" NOT NULL,
    target_country text COLLATE pg_catalog."default" NOT NULL,
    year numeric(4, 0) NOT NULL,
    affinity numeric,
    source_country_code character varying(3) COLLATE pg_catalog."default",
    target_country_code character varying(3) COLLATE pg_catalog."default",
    CONSTRAINT dyad_pkey PRIMARY KEY (source_country, target_country, year)
);

DROP TABLE IF EXISTS public.event;

CREATE TABLE IF NOT EXISTS public.event
(
    id numeric NOT NULL,
    year numeric(4, 0),
    source_name text COLLATE pg_catalog."default",
    source_sectors text COLLATE pg_catalog."default",
    source_country text COLLATE pg_catalog."default",
    source_country_code character varying(3) COLLATE pg_catalog."default",
    text text COLLATE pg_catalog."default",
    cameo_code text COLLATE pg_catalog."default",
    intensity numeric,
    target_name text COLLATE pg_catalog."default",
    target_sectors text COLLATE pg_catalog."default",
    target_country text COLLATE pg_catalog."default",
    target_country_code character varying(3) COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    district text COLLATE pg_catalog."default",
    province text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    latitude numeric,
    longitude numeric,
    CONSTRAINT event_pkey PRIMARY KEY (id)
);
END;